### ISSUE TITLE
一些关于任选课的问题。

### ISSUE THREAD

**Issue by Ma-Weijian** [Oneliey/BUPT-SCS-Courses#22]
请问量子计算导论今年是变成了计科的专业选修吗？
以及，一些类似区块链应用技术这种的任选课我们要不要单独开一个目录，给有兴趣的学弟学妹康康？

**Comment by Oneliey** [comment]
量子计算导论应该叫xx标杆课，好像不在培养方案上，选课的时候好像是一起选的，还有类似的几门。
区块链应用技术这种的任选课 指的是全校的任选课吗？我觉得这个建议不错，可以再单独开一个文件夹，目录放到软件工程专业后面即可，欢迎PR~

**Comment by yts1999** [comment]
还有 无线传感器网络

> 量子计算导论应该叫xx标杆课，不在培养方案上，选课的时候好像是一起选的，还有类似的几门。
> 区块链应用技术这种的任选课 指的是全校的任选课吗？我觉得这个建议不错，可以再单独开一个文件夹，目录放到软件工程专业后面即可，欢迎PR~

**Comment by happylittlecat2333** [comment]
"量子计算和无线传感器网络是标杆课，是专业选修课技术拓展模块，这个是学校的鼓励政策，虽然不在培养方案但是可以算专业选修。"
