### ISSUE TITLE
第4学期课程设计

### ISSUE THREAD

**Issue by Bang0518** [oneliey/BUPT-SCS-Courses#48]
培养方案上在第四学期设置了 **数字逻辑与数字系统课程设计** _与_ **计算机组成原理课程设计** ，两者二选一。
但在选课指南中并未有设置条目，是否可以于近期进行补充呢😝

**Comment by Bang0518** [comment]
附：培养方案截图
![1](https://user-images.githubusercontent.com/30588114/156814178-bed54315-e021-4a27-9aa3-dbdd5f1503af.png)

**Comment by oneliey** [comment]
好的，我联系相关学长进行补充

**Comment by oneliey** [comment]
好的，我联系相关学长学姐进行补充

**Comment by oneliey** [comment]
以添加 #55

**Comment by Bang0518** [comment]
thanks~
